<?php
/**
 * @package    WBTY Payments
 *
 * @copyright  Copyright (C) 2005 - 2012 Open Source Matters, Inc. All rights reserved.
 * @license    GNU General Public License version 2 or later; see LICENSE
 */

defined('JPATH_PLATFORM') or die;

require_once(dirname(__FILE__) .DS. "WBTYPaymentsGatewayModel.php");

class WBTYPaymentsPaypal_standard extends WBTYPaymentsGatewayModel {

	function __construct($properties = null) {

		// Call the function to get the merchant and post data
		$this->info = parent::getGateway();

		/**
		# API user: The user that is identified as making the call. you can
		# also use your own API username that you created on PayPal�s sandbox
		# or the PayPal live site
		*/
		$this->API_UserName=$this->info['merchant']['api_username'];


		/**
		# API_password: The password associated with the API user
		# If you are using your own API username, enter the API password that
		# was generated by PayPal below
		# IMPORTANT - HAVING YOUR API PASSWORD INCLUDED IN THE MANNER IS NOT
		# SECURE, AND ITS ONLY BEING SHOWN THIS WAY FOR TESTING PURPOSES
		*/
		$this->API_Password=$this->info['merchant']['api_password'];

		/**
		# API_Signature:The Signature associated with the API user. which is generated by paypal.
		*/
		$this->API_Signature=$this->info['merchant']['api_signature'];

		/**
		# Endpoint: this is the server URL which you have to connect for submitting your API request.
		*/
		$this->API_Endpoint ='https://api-3t.sandbox.paypal.com/nvp';

		/**
		# Version: this is the API version in the request.
		# It is a mandatory parameter for each API request.
		# The only supported value at this time is 2.3
		*/
		$this->version=2.3;

		$this->subject = '';

		// below three are needed if used permissioning
		$this->AUTH_token='';

		$this->AUTH_signature='';

		$this->AUTH_timestamp='';

		$this->USE_PROXY = FALSE;

		/**
		# PROXY_HOST and PROXY_PORT will be read only if USE_PROXY is set to TRUE

		$this->PROXY_HOST = 127.0.0.1;
		$this->PROXY_PORT = 808;
		*/

		/* Define the PayPal URL. This is the URL that the buyer is
		   first sent to to authorize payment with their paypal account
		   change the URL depending if you are testing on the sandbox
		   or going to the live PayPal site
		   For the sandbox, the URL is
		   https://www.sandbox.paypal.com/webscr&cmd=_express-checkout&token=
		   For the live site, the URL is
		   https://www.paypal.com/webscr&cmd=_express-checkout&token=
		   */
		$this->PAYPAL_URL = 'https://www.sandbox.paypal.com/webscr&cmd=_express-checkout&token=';

		// Ack related constants
		$this->ACK_SUCCESS = 'SUCCESS';
		$this->ACK_SUCCESS_WITH_WARNING = 'SUCCESSWITHWARNING';

		parent::__construct($properties);
	}


	function process_cc() {
		return false;
	}

	function verify_payment() {
		$referenceId = JFactory::getApplication()->input->get('referenceId', '');
		$order_id = ltrim($referenceId, 'wbtypayments-');

		if (!$order_id) {
			return false;
		}

		return $order_id;
	}

	function setPaid($order_id = 0, $user_id = 0, $clear = true) {
		parent::setPaid($order_id, $user_id, $clear);
 	}

}
